# Generated by Django 2.2.14 on 2020-07-25 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.Review'),
            preserve_default=False,
        ),
    ]
